### ISSUE TITLE
Simulate LSST Observations of Dwarf Galaxies

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/LSSTDarkMatter#1]
We would like to use [imSim](LSSTDESC/imSim) to simulate images of Local Group dwarf galaxies and then run the LSSST software stack to perform source finding and photometry.

We are hoping to get this off the ground in the Wednesday mini-hack.

**Comment by kadrlica** [comment]
Using [ugali](DarkEnergySurvey/ugali) and [dsphsim](kadrlica/dsphsim) module to simulation the spatial and color magnitude distribution of a dwarf galaxy with Mv = -12, rh = 300 pc, and D = 1 Mpc. LSST single-pass g-band detection threshold (approximate) is shown with black dashed line.

![simulated_kernel](https://cloud.githubusercontent.com/assets/5605123/24725824/cf8cae5a-1a15-11e7-8dd4-421b680a8049.png)
![simulated_isochrone](https://cloud.githubusercontent.com/assets/5605123/24725820/ccf6e156-1a15-11e7-8647-3a26cabd9930.png)

**Comment by kadrlica** [comment]
Adapting output to match the [Instance Catalog](https://confluence.lsstcorp.org/display/PHOSIM/Instance+Catalog) interface expected by imSim and phosim. Started with [tiny_instcat.txt](https://github.com/LSSTDESC/imSim/blob/3e1259c0c42d553b3db61fd1edead865c0934dad/tests/tiny_instcat.txt) as an example. Stars in the dwarf galaxy are modeled as individual point sources when they are brighter that g < 25 mag. Below this threshold we generate a single extended source with an exponential profile (really a `sersic2d` model) with a normalization set by the integrated flux of the sub-threshold sources. A snippet of the catalog is pasted below

```
# instcat file written by dsphsim
rightascension 54.0
declination -54.0
mjd 59797.285409
altitude 43.6990272
azimuth 73.7707957
filter 1
rotskypos 69.092293
rottelpos 0.0
dist2moon 145.1095257
moonalt -11.1383568
moondec -18.770212
moonphase 59.628883
moonra 230.9832941
nsnap 2
obshistid 1
seed 1
seeing 0.761376
rawSeeing 0.761376
FWHMgeom 1.210734
FWHMeff 1.409653
sunalt -59.1098785
vistime 33.0
object 0    54.000000   -54.000000    13.328449 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 sersic2d    36.857143    36.857143 0 1 none CCM 0.0 3.1
object 3659    54.003472   -54.004041    24.874301 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 5532    54.065444   -53.994095    24.884787 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 6355    53.993503   -53.988691    24.966792 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 11194    54.043986   -53.924732    24.560148 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 24307    54.048338   -53.978983    24.075011 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 25715    54.004695   -53.987490    24.010676 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 27747    53.995604   -54.025702    23.027644 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 32411    54.020216   -54.016401    24.889610 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
object 33282    54.006759   -54.008692    24.684490 starSED/phoSimMLT/lte031-4.5-1.0a+0.4.BT-Settl.spec.gz 0 0 0 0 0 0 point none CCM 0.0 3.1
```

**Comment by kadrlica** [comment]
@segasai has imSim up and running with the LSST stack and generated at image using the instance catalog.

![objects_sersic2d](https://cloud.githubusercontent.com/assets/5605123/24726471/29d29e18-1a18-11e7-831a-d059c9548dd4.png)

**Comment by kadrlica** [comment]
@rbliu has put together a script to run LSST source extraction on these images. @segasai has generated g- and r-band images and can create a CMD!

![cmd_output](https://cloud.githubusercontent.com/assets/5605123/24729375/83379fe8-1a23-11e7-8188-4d28be582cc9.png)

**Comment by kadrlica** [comment]
Wednesday's hack is done and this issue is successfully closed.

**Comment by drphilmarshall** [comment]
ROCK. ON.

On Wed, Apr 5, 2017 at 6:52 PM, Alex Drlica-Wagner <notifications@github.com
