### ISSUE TITLE
Simulate a tidal stream

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/LSSTDarkMatter#2]
We would like to extend the infrastructure that was developed during the Wednesday mini-hack to the simulation of a stellar stream.

**Comment by kadrlica** [comment]
@sazabi4 has modified the `generateInstCat.py` script to simulate a line of Gaussians. @kadrlica has installed `imsim` and is testing. A first run of a stream with width=0.3 deg and length=3.0 deg produces stars, but is not very impressive...

![test](https://cloud.githubusercontent.com/assets/5605123/24785414/37a0dbb0-1b1f-11e7-9bc0-24d30fca285b.png)

**Comment by kadrlica** [comment]
A new day a new InstCat file... this one has a width=0.05 deg and length=0.3deg with a surface brightness of 24 mag/arcsec^2. This catalog makes a pretty picture.

![stream0 05_0 3_24](https://cloud.githubusercontent.com/assets/5605123/24786283/ddd64640-1b25-11e7-9673-56ef42a9d2e9.jpeg)

**Comment by kadrlica** [comment]
And here is just the unresolved component.
![stream0 05_0 3_24_diffuse](https://cloud.githubusercontent.com/assets/5605123/24786406/d755deec-1b26-11e7-893c-339dcbe31bd5.jpeg)

**Comment by sazabi4** [comment]
@segasai Can you suggest some range of parameters for the stream in terms of 
width (pc or deg), length (pc or deg), distance(kpc or dm), surface brightness
so that we can make some mock images. It would also be interesting to maybe make a dwarf and a stream next to it (at same distance)

**Comment by segasai** [comment]
@sazabi4 I'd say the interesting range of parameters is:
surface brightness 28-31 mag/sq.arcsec, sizes 20 pc - 1 kpc, and distances 1Mpc, 10Mpc,  50 Mpc

**Comment by sazabi4** [comment]
Two examples here:

1. width=20pc, length=300pc, SB=27, distance=100kpc

<img width="764" alt="screen shot 2017-04-07 at 12 30 46 pm" src="https://cloud.githubusercontent.com/assets/7751063/24812449/bf4549e6-1b8f-11e7-916f-aca05565dd88.png">

2. width=50pc, length=1000pc, SB=27, distance=1000kpc

<img width="760" alt="screen shot 2017-04-07 at 12 30 32 pm" src="https://cloud.githubusercontent.com/assets/7751063/24812460/c64eb786-1b8f-11e7-843d-6889deb1dd11.png"> 

FOV of the images are both around 0.1 deg (or 1/3 of the 1 LSST CCD chip)

**Comment by segasai** [comment]
Looks very cool!

**Comment by sazabi4** [comment]
a wrapper run_generate.py has been added to generate a grid of catalogs with different surface brightness, distance, stream width, etc. After running 
python run_generate.py
the catalog will be genrated in ~/catalogs/ folder, then run
python doimsim.py
to generate the associated images under  ~/catalogs/

A detailed readme file has been added. Also comments for each python code has been added.

This hack task "streamsim" has been completed. The image fits files are available by request -- too big to upload.
