### ISSUE TITLE
Simulate mass function constraints from strong lenses

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/LSSTDarkMatter#3]
We would like to estimate how well the LSST strong lensing sample will be to constrain the dark matter subhalo mass function. We plan to start by replicating the analysis framework in [Vegetti & Koopmans, 2009](https://arxiv.org/abs/0903.4752).

**Comment by kadrlica** [comment]
@yyzhang has looked into Section 2.4 or Vegetti & Koopmans and has assembled a list of strong lensing masses within 0.6" of the Einstein radius for the SLACS lens sample [here](https://github.com/LSSTDESC/LSSTDarkMatter/tree/fe3fc77b79adb0c15229aa9750cc4f7779f10b15/stronglens/stronglens_substructure).

**Comment by kadrlica** [comment]
It looks like the Poisson part of the likelihood *might* be working
![poisson_contours](https://cloud.githubusercontent.com/assets/5605123/24806466/993b0c6e-1b7a-11e7-9ff7-e40e50cc85e7.png)

**Comment by kadrlica** [comment]
I've added an [ipython notebook](https://github.com/LSSTDESC/LSSTDarkMatter/blob/master/stronglens/SubstructureLikelihood.ipynb) documenting and replicating the statistical method in Vegetti & Koopmans, 2009.

A pretty plot of the likelihood surface for a random realization of 10 lens systems (without mass measurement uncertainty) should be enough to close this issue.

![vk09_nlens10](https://cloud.githubusercontent.com/assets/5605123/24845415/7343436a-1d77-11e7-8869-4a3c1f6694ec.png)

**Comment by DouglasLeeTucker** [comment]
Nice!  Thanks for posting the ipython notebook, Alex!

Best regards,
Douglas


--
=======================================================================
Douglas L. Tucker
Fermilab                        Tel:    +1-630-840-2267
MS 127                          FAX:    +1-630-840-8274
PO Box 500                      E-mail: dtucker@fnal.gov
Batavia, IL 60510 USA           http://home.fnal.gov/~dtucker/
=======================================================================
