### ISSUE TITLE
Remove fits image permanently

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/LSSTDarkMatter#4]
The large file `satsim/lsst_e_1_R_2_2_S_1_1_g.fits` keeps coming back to life (just pulled and it re-appeared in my repo). We need to clean this (and get everyone to re-clone if necessary...)

**Comment by kadrlica** [comment]
I think I was responsible for re-adding the file. I've used `bfg` to remove it, but I'm not sure if it's really gone...

**Comment by segasai** [comment]
I've re-cloned the repo and don't see the .fits  file.

**Comment by kadrlica** [comment]
Thanks. If you still have the old clone around, could you try pulling and see if it appears?

**Comment by segasai** [comment]
No, I've just deleted my last old clone...

**Comment by sazabi4** [comment]
I just did a git pull and I did not see the fit file. But when I did git pull yesterday, I don't see the fits file either.

**Comment by kadrlica** [comment]
Ok, that's good. I think that means the clean up worked (as long as no one pushes the file again accidentally).

**Comment by TallJimbo** [comment]
Note that whether or not you see the file on master is not an indication of whether or not it's gone from the repo; it needs to be removed from all commits in the history of all branches and tags to be avoid having it take up space.  `bfg` should have done that, but if anyone pushes any branch with the file in its history, it will come back.
