### ISSUE TITLE
Evaluation of cadence for MACHO searches

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/LSSTDarkMatter#5]
@wadawson  and @annis have been looking into evaluating the cadence of LSST for MACHO searches.

**Comment by annis** [comment]
[desc-hack-week-april-2017.pdf](https://github.com/LSSTDESC/LSSTDarkMatter/files/906086/desc-hack-week-april-2017.pdf)
![desc-macho](https://cloud.githubusercontent.com/assets/3037250/24807949/d24c53be-1b7f-11e7-91a6-9f8c7778b341.png)

**Comment by annis** [comment]
Hack completed

**Comment by wadawson** [comment]
@annis This looks interesting. I will try to dig into the details once I am back from vacation later this week. We should chat more offline at some point.

**Comment by annis** [comment]
That sounds great, Will. -Jim
